# Generated by Django 5.1.2 on 2025-05-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='colors',
            field=models.ManyToManyField(related_name='character', through='core.To_own', to='core.color'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(related_name='character', through='core.To_in', to='core.movie'),
        ),
        migrations.AlterField(
            model_name='character',
            name='universes',
            field=models.ManyToManyField(related_name='character', through='core.Belong', to='core.univers'),
        ),
    ]
