# Generated by Django 5.1.2 on 2025-04-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_character_colors_remove_character_movies_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='character',
        #     name='univers',
        # ),
    ]
