# Generated by Django 5.1.2 on 2025-05-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_character_colors_alter_character_movies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belong',
            old_name='universe',
            new_name='univers',
        ),
        migrations.RemoveField(
            model_name='character',
            name='universes',
        ),
        migrations.AddField(
            model_name='character',
            name='univers',
            field=models.ManyToManyField(related_name='characters', through='core.Belong', to='core.univers'),
        ),
        migrations.AlterField(
            model_name='character',
            name='colors',
            field=models.ManyToManyField(related_name='characters', through='core.To_own', to='core.color'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(related_name='characters', through='core.To_in', to='core.movie'),
        ),
    ]
